DROP VIEW VIEW_ADRES_OBJV;
DROP VIEW VIEW_ODZNAKI_OBJV;
DROP VIEW VIEW_POLISY_OBJV;
DROP VIEW VIEW_ZDJECIA_DOWODY_OBJV;
DROP VIEW VIEW_ZDJECIA_OBJV;

DROP TABLE KOMISARIAT_OBJTAB;
DROP TABLE policjant_objtab;
DROP TABLE samochod_objtab;
DROP TABLE sprawa_objtab;
DROP TABLE odcisk_objtab;

DROP TYPE sprawa_objtyp;
DROP TYPE swiadek_ntabtyp;

DROP TYPE dowod_ntabtyp;
DROP TYPE dowod_objtyp;
DROP TYPE samochod_objtyp;

DROP TYPE policjant_objtyp;
DROP TYPE polisa_ntabtyp;
DROP TYPE osprzet_ntabtyp;
DROP TYPE odznaka_ntabtyp;
DROP TYPE odcisk_objtyp;
DROP TYPE swiadek_objtyp;
DROP TYPE osoba_objtyp;
DROP TYPE zdjecie_vartyp;

DROP TYPE zdjecie_objtyp;
DROP TYPE komisariat_objtyp;
DROP TYPE sprzet_objtyp;
DROP TYPE polisa_objtyp;
DROP TYPE osprzet_objtyp;
DROP TYPE odznaka_objtyp;

DROP TYPE adres_objtyp;



--------- Skrypt obiektowy --------------
--------- Baza policyjna ----------------

CREATE OR REPLACE TYPE adres_objtyp AS OBJECT
(
	ulica VARCHAR2(10),
	nr_domu VARCHAR2(4),
	nr_mieszkania VARCHAR2(4),
	miasto VARCHAR2(10),
	kod VARCHAR2(6),
	MEMBER FUNCTION returnKodWithSign RETURN VARCHAR,
	MAP MEMBER FUNCTION nr_domu_kol RETURN VARCHAR
);
/

CREATE OR REPLACE TYPE BODY adres_objtyp AS
	MEMBER FUNCTION returnKodWithSign RETURN VARCHAR IS
	newKOD varchar(7);
	BEGIN
		newKOD := SUBSTR(SELF.kod,1,3) || '-' || SUBSTR(SELF.kod,3,6);
		RETURN newKOD;
	END;
    MAP MEMBER FUNCTION nr_domu_kol RETURN VARCHAR IS
    BEGIN
        RETURN CONCAT(ulica,nr_domu);
    END nr_domu_kol;
END;
/

CREATE OR REPLACE TYPE odznaka_objtyp AS OBJECT
(
	nazwa_odznaki varchar(30),
	cel varchar(30)
);
/

CREATE OR REPLACE TYPE osprzet_objtyp AS OBJECT
(
	nazwa varchar(30),
	wymagany_przeglad date
);
/



CREATE OR REPLACE TYPE polisa_objtyp AS OBJECT
(
	typ_polisy varchar(30),
	data_waznosci date
);
/

CREATE OR REPLACE TYPE sprzet_objtyp AS OBJECT
(
	nazwa varchar(30),
	data_zakupu date,
	gwarancja NUMBER(1)
);
/

CREATE OR REPLACE TYPE komisariat_objtyp AS OBJECT
(
	id number(5),
	opis varchar(30),
	adres adres_objtyp,
	numer_telefonu varchar(30),
	email varchar(30),
	powiat varchar(30),
	wojewodztwo varchar(30),
	ORDER MEMBER FUNCTION porownaj (k komisariat_objtyp) RETURN INTEGER
);
/
CREATE TYPE BODY komisariat_objtyp AS
	ORDER MEMBER FUNCTION porownaj (k komisariat_objtyp) RETURN INTEGER IS
	BEGIN 
		if id < k.id THEN 
		RETURN -1;
		ELSIF ID > K.ID THEN
		RETURN 1;
		ELSE RETURN 0;
		END IF;
	END;
END;
/
CREATE OR REPLACE TYPE zdjecie_objtyp AS OBJECT
(
	opis varchar(30),
	data_zebrania date,
	obrazek varchar(1024),
	STATIC FUNCTION printTyp RETURN NUMBER
);
/	

CREATE OR REPLACE TYPE BODY zdjecie_objtyp AS
	STATIC FUNCTION printTyp RETURN NUMBER IS
	BEGIN
		DBMS_OUTPUT.PUT_LINE('Typ sklada sie z '||' opis '||' data zebrania oraz obrazek');  
		RETURN 0;
	END printTyp;
END;
/

CREATE OR REPLACE TYPE zdjecie_vartyp AS VARRAY(5) OF zdjecie_objtyp;
/


CREATE OR REPLACE TYPE osoba_objtyp AS OBJECT
(
	id number(5),
	imie varchar(30),
	nazwisko varchar(30),
	pesel varchar(11),
	data_urodzenia date,
	adres adres_objtyp,
	numer_telefonu varchar(30),
	email varchar(30),
	zdjecia zdjecie_vartyp

) NOT FINAL;
/

CREATE OR REPLACE TYPE swiadek_objtyp UNDER osoba_objtyp
	(
	typ varchar(30)
	) NOT FINAL;
	/
	
CREATE OR REPLACE TYPE odcisk_objtyp AS OBJECT
(
	id number(5),
	opis varchar(30),
	data_zebrania date,
	id_osob_fk REF osoba_objtyp,
	grafika varchar(1024)
);
/
	
CREATE OR REPLACE TYPE odznaka_ntabtyp AS TABLE OF odznaka_objtyp;
/

CREATE OR REPLACE TYPE osprzet_ntabtyp AS TABLE OF osprzet_objtyp;
/
	
CREATE OR REPLACE TYPE polisa_ntabtyp AS TABLE OF polisa_objtyp;
/
	
CREATE OR REPLACE TYPE policjant_objtyp UNDER osoba_objtyp
	(
	stopien varchar(30),
	odznaki odznaka_ntabtyp,
	id_komis_fk REF komisariat_objtyp,
	osprzet osprzet_ntabtyp
	) NOT FINAL;
	/
	
CREATE OR REPLACE TYPE samochod_objtyp AS OBJECT
(
	id varchar(5),
	marka varchar(30),
	model varchar(30),
	silnik varchar(30),
	spalanie varchar(30),
	kolor varchar(30),
	nr_rejestracyjny varchar(30),
	id_komis_fk REF komisariat_objtyp,
	polisy polisa_ntabtyp
);
/


CREATE OR REPLACE TYPE dowod_objtyp AS OBJECT
(
	opis varchar(30),
	data_zebrania date,
	zdjecia zdjecie_vartyp
);
/

CREATE OR REPLACE TYPE dowod_ntabtyp AS TABLE OF dowod_objtyp;
/
CREATE OR REPLACE TYPE swiadek_ntabtyp AS TABLE OF swiadek_objtyp;
/




CREATE OR REPLACE TYPE sprawa_objtyp AS OBJECT
(	
	id varchar(5),
	opis varchar(30),
	typ varchar(30),
	dowody dowod_ntabtyp,
	id_komis_fk REF komisariat_objtyp,
	swiadkowie swiadek_ntabtyp
);
/





CREATE TABLE komisariat_objtab OF komisariat_objtyp (id PRIMARY KEY);
/
CREATE TABLE policjant_objtab OF policjant_objtyp (id PRIMARY KEY)
NESTED TABLE osprzet STORE AS ntab_osprzet_policjant
NESTED TABLE odznaki STORE AS ntab_odznaki_policjant;
/


CREATE TABLE samochod_objtab OF samochod_objtyp(id PRIMARY KEY)
NESTED TABLE polisy STORE AS ntab_polisy_samochod;
/
CREATE TABLE sprawa_objtab OF sprawa_objtyp(id PRIMARY KEY)
NESTED TABLE dowody STORE AS ntab_dowody_sprawa
NESTED TABLE swiadkowie STORE AS ntab_swiadkowie_sprawa;
/
CREATE TABLE odcisk_objtab OF odcisk_objtyp (id PRIMARY KEY);
/

------------------- INSERT ------------------------------
INSERT INTO SPRAWA_OBJTAB VALUES(1, 'Porwanie JANA K', 'Cywilna', NULL, NULL, NULL);
INSERT INTO SPRAWA_OBJTAB VALUES(2,'Kradziez zegarka','Cywilna', NULL, NULL, NULL);
INSERT INTO SPRAWA_OBJTAB VALUES(3,'Kradziez roweru','Cywilna', NULL, NULL, NULL);
INSERT INTO SPRAWA_OBJTAB VALUES(4,'Grozby karalne','Cywilna', NULL, NULL, NULL);
INSERT INTO SPRAWA_OBJTAB VALUES(5,'Oszustwa podatkowe','Cywilna', NULL, NULL, NULL);


INSERT INTO SAMOCHOD_OBJTAB VALUES(1,'Dacia', 'Duster', '2.4 JTD', '11.2', 'Morelowy', 'CTF1233', NULL, NULL);
INSERT INTO SAMOCHOD_OBJTAB VALUES(2,'Skoda', 'Fabia', '2.4 TDI', '5.5', 'Biały', 'CTF1321', NULL, NULL);
INSERT INTO SAMOCHOD_OBJTAB VALUES(3,'Peugeot', '508', '5.4 HDI', '8.8', 'Szary', 'CDG1233', NULL, NULL);
INSERT INTO SAMOCHOD_OBJTAB VALUES(4,'Mercedes', 'A320', '1.9 benzyna', '13.2', 'Czarny', 'DWR1233', NULL, NULL);
INSERT INTO SAMOCHOD_OBJTAB VALUES(5,'Bmw', 'i320', '3.2', '11.2', 'Zielony', 'BRO1233', NULL, NULL);


INSERT INTO POLICJANT_OBJTAB VALUES(1,'Jan','Kowalski', '99120312345', TO_DATE('03-12-1999','DD-MM-YYYY'), ADRES_OBJTYP('Lewa', '1a', '12', 'Notki','12345'), '123421312', 'asdas@dsa.pl',NULL,'NADINSPEKTOR',NULL, NULL, NULL);
INSERT INTO POLICJANT_OBJTAB VALUES(2,'Jan','Nowak', '92120312345', TO_DATE('03-12-1992','DD-MM-YYYY'), ADRES_OBJTYP('Biala', '31','12' , 'Pionki','12342'), '123123123123421312', 'dasddas@dsas@dsdasa.pl',NULL,'POSTERUNKOWY',NULL, NULL, NULL);
INSERT INTO POLICJANT_OBJTAB VALUES(3,'Tomasz','Wolski', '54110512345', TO_DATE('05-11-1954','DD-MM-YYYY'),ADRES_OBJTYP('Mewa', '62', '1', 'Nysa','12342'), '321312', 'dasdasdas@dsadas.pl',NULL,'STARSZY POSTERUNKOWY',NULL, NULL, NULL);
INSERT INTO POLICJANT_OBJTAB VALUES(4,'Andrzej','Polski', '33120512345', TO_DATE('05-12-1933','DD-MM-YYYY'),ADRES_OBJTYP('Rakiet', '11', '2', 'Wurek','12342'), '3213123321', 'fasd@dsdsaa.pl',NULL,'SIERŻANT',NULL, NULL, NULL);
INSERT INTO POLICJANT_OBJTAB VALUES(5,'Hanna','Miara', '67090312345', TO_DATE('03-09-1967','DD-MM-YYYY'), ADRES_OBJTYP('Pomostowa', '34', '6', 'Mopsik','12342'), '312312312', 'sds@dsdasa.com',NULL,'SIERŻANT',NULL, NULL, NULL);


INSERT INTO KOMISARIAT_OBJTAB VALUES(1,'Komisariat Powiatowy',ADRES_OBJTYP('Pomostowa', '22', '1', 'Mopsik','12342'), '3213123123', 'dasdsada@dasdas.com', 'Hubski', 'Lubuskie');
INSERT INTO KOMISARIAT_OBJTAB VALUES(2,'Komisariat miejski',ADRES_OBJTYP('Miastowa', '13', '2', 'Klawiur','32133'), '2312312312', 'dadsaada@dasdas.com', 'Klawiurski', 'Lubuskie');
INSERT INTO KOMISARIAT_OBJTAB VALUES(3,'Komisariat wiejski',ADRES_OBJTYP('Wiejska', '23', '3', 'Masun','12342'), '312321312', 'ddasdasdsada@dasdas.com', 'Masunski', 'Lubuskie');
INSERT INTO KOMISARIAT_OBJTAB VALUES(4,'Komisariat Wojewodzki',ADRES_OBJTYP('Grudzia', '21', '4', 'Szczecin','12313'), '6546445324', 'dasdddsada@dasdas.com', 'Szczecinski', 'Zachodniopomorskie');
INSERT INTO KOMISARIAT_OBJTAB VALUES(5,'Komisariat pomocniczy',ADRES_OBJTYP('Gdanska', '1', '5', 'Torun','12342'), '7657656756', 'dasdsddada@dasdas.com', 'Torunski', 'Lubuskie');

UPDATE SAMOCHOD_OBJTAB SET ID_KOMIS_FK = (SELECT REF(K) FROM KOMISARIAT_OBJTAB K WHERE ID = 1) WHERE ID = 1;
UPDATE SAMOCHOD_OBJTAB SET ID_KOMIS_FK = (SELECT REF(K) FROM KOMISARIAT_OBJTAB K WHERE ID = 2) WHERE ID = 2;
UPDATE SAMOCHOD_OBJTAB SET ID_KOMIS_FK = (SELECT REF(K) FROM KOMISARIAT_OBJTAB K WHERE ID = 3) WHERE ID = 3;
UPDATE SAMOCHOD_OBJTAB SET ID_KOMIS_FK = (SELECT REF(K) FROM KOMISARIAT_OBJTAB K WHERE ID = 4) WHERE ID = 4;
UPDATE SAMOCHOD_OBJTAB SET ID_KOMIS_FK = (SELECT REF(K) FROM KOMISARIAT_OBJTAB K WHERE ID = 5) WHERE ID = 5;

UPDATE SAMOCHOD_OBJTAB SET POLISY = POLISA_NTABTYP();


INSERT INTO TABLE(SELECT S.POLISY FROM SAMOCHOD_OBJTAB S WHERE ID = 1) VALUES (POLISA_OBJTYP('OC', TO_DATE('12-03-2022','DD-MM-YYYY')));
INSERT INTO TABLE(SELECT S.POLISY FROM SAMOCHOD_OBJTAB S WHERE ID = 2) VALUES (POLISA_OBJTYP('OC', TO_DATE('12-03-2022','DD-MM-YYYY')));
INSERT INTO TABLE(SELECT S.POLISY FROM SAMOCHOD_OBJTAB S WHERE ID = 3) VALUES (POLISA_OBJTYP('OC', TO_DATE('12-03-2022','DD-MM-YYYY')));
INSERT INTO TABLE(SELECT S.POLISY FROM SAMOCHOD_OBJTAB S WHERE ID = 4) VALUES (POLISA_OBJTYP('OC', TO_DATE('12-03-2022','DD-MM-YYYY')));
INSERT INTO TABLE(SELECT S.POLISY FROM SAMOCHOD_OBJTAB S WHERE ID = 5) VALUES (POLISA_OBJTYP('OC', TO_DATE('12-03-2022','DD-MM-YYYY')));

UPDATE POLICJANT_OBJTAB SET ZDJECIA = ZDJECIE_VARTYP(ZDJECIE_OBJTYP('Zdjęcie profilowe', TO_DATE('11-11-2021','DD-MM-YYYY'), '2211174522912251234'),ZDJECIE_OBJTYP('Zdjęcie profilowe2', TO_DATE('11-11-2021','DD-MM-YYYY'), '2211174522912251234')) WHERE ID = 1;
UPDATE POLICJANT_OBJTAB SET ZDJECIA = ZDJECIE_VARTYP(ZDJECIE_OBJTYP('Zdjęcie profilowe', TO_DATE('11-11-2021','DD-MM-YYYY'), '2211174522912251234'),ZDJECIE_OBJTYP('Zdjęcie profilowe2', TO_DATE('11-11-2021','DD-MM-YYYY'), '2211174522912251234')) WHERE ID = 2;
UPDATE POLICJANT_OBJTAB SET ZDJECIA = ZDJECIE_VARTYP(ZDJECIE_OBJTYP('Zdjęcie profilowe', TO_DATE('11-11-2021','DD-MM-YYYY'), '2211174522912251234'),ZDJECIE_OBJTYP('Zdjęcie profilowe2', TO_DATE('11-11-2021','DD-MM-YYYY'), '2211174522912251234')) WHERE ID = 3;
UPDATE POLICJANT_OBJTAB SET ZDJECIA = ZDJECIE_VARTYP(ZDJECIE_OBJTYP('Zdjęcie profilowe', TO_DATE('11-11-2021','DD-MM-YYYY'), '2211174522912251234'),ZDJECIE_OBJTYP('Zdjęcie profilowe2', TO_DATE('11-11-2021','DD-MM-YYYY'), '2211174522912251234')) WHERE ID = 4;
UPDATE POLICJANT_OBJTAB SET ZDJECIA = ZDJECIE_VARTYP(ZDJECIE_OBJTYP('Zdjęcie profilowe', TO_DATE('11-11-2021','DD-MM-YYYY'), '2211174522912251234'),ZDJECIE_OBJTYP('Zdjęcie profilowe2', TO_DATE('11-11-2021','DD-MM-YYYY'), '2211174522912251234')) WHERE ID = 5;

UPDATE POLICJANT_OBJTAB SET ODZNAKI = ODZNAKA_NTABTYP();

INSERT INTO TABLE(SELECT P.ODZNAKI FROM POLICJANT_OBJTAB P WHERE ID = 1) VALUES (ODZNAKA_OBJTYP('Policyjna','Potwierdzenie uprawnien'));
INSERT INTO TABLE(SELECT P.ODZNAKI FROM POLICJANT_OBJTAB P WHERE ID = 2) VALUES (ODZNAKA_OBJTYP('Policyjna','Potwierdzenie uprawnien'));
INSERT INTO TABLE(SELECT P.ODZNAKI FROM POLICJANT_OBJTAB P WHERE ID = 3) VALUES (ODZNAKA_OBJTYP('Policyjna','Potwierdzenie uprawnien'));
INSERT INTO TABLE(SELECT P.ODZNAKI FROM POLICJANT_OBJTAB P WHERE ID = 4) VALUES (ODZNAKA_OBJTYP('Policyjna','Potwierdzenie uprawnien'));
INSERT INTO TABLE(SELECT P.ODZNAKI FROM POLICJANT_OBJTAB P WHERE ID = 5) VALUES (ODZNAKA_OBJTYP('Policyjna','Potwierdzenie uprawnien'));

INSERT INTO TABLE(SELECT P.ODZNAKI FROM POLICJANT_OBJTAB P WHERE ID = 1) VALUES (ODZNAKA_OBJTYP('Dzielny policjant','Nagroda'));

UPDATE POLICJANT_OBJTAB SET ID_KOMIS_FK = (SELECT REF(K) FROM KOMISARIAT_OBJTAB K WHERE ID = 1) WHERE ID = 1;
UPDATE POLICJANT_OBJTAB SET ID_KOMIS_FK = (SELECT REF(K) FROM KOMISARIAT_OBJTAB K WHERE ID = 2) WHERE ID = 2;
UPDATE POLICJANT_OBJTAB SET ID_KOMIS_FK = (SELECT REF(K) FROM KOMISARIAT_OBJTAB K WHERE ID = 3) WHERE ID = 3;
UPDATE POLICJANT_OBJTAB SET ID_KOMIS_FK = (SELECT REF(K) FROM KOMISARIAT_OBJTAB K WHERE ID = 4) WHERE ID = 4;
UPDATE POLICJANT_OBJTAB SET ID_KOMIS_FK = (SELECT REF(K) FROM KOMISARIAT_OBJTAB K WHERE ID = 5) WHERE ID = 5;

UPDATE POLICJANT_OBJTAB SET OSPRZET = OSPRZET_NTABTYP();

INSERT INTO TABLE(SELECT P.OSPRZET FROM POLICJANT_OBJTAB P WHERE ID = 1) VALUES (OSPRZET_OBJTYP('Gaz łzawiacy', TO_DATE('03-01-2022','DD-MM-YYYY')));
INSERT INTO TABLE(SELECT P.OSPRZET FROM POLICJANT_OBJTAB P WHERE ID = 2) VALUES (OSPRZET_OBJTYP('Pałka teleskopowa', TO_DATE('03-01-2022','DD-MM-YYYY')));
INSERT INTO TABLE(SELECT P.OSPRZET FROM POLICJANT_OBJTAB P WHERE ID = 3) VALUES (OSPRZET_OBJTYP('Pistolet hukowy', TO_DATE('03-01-2022','DD-MM-YYYY')));
INSERT INTO TABLE(SELECT P.OSPRZET FROM POLICJANT_OBJTAB P WHERE ID = 4) VALUES (OSPRZET_OBJTYP('Kajdanki', TO_DATE('03-01-2022','DD-MM-YYYY')));
INSERT INTO TABLE(SELECT P.OSPRZET FROM POLICJANT_OBJTAB P WHERE ID = 5) VALUES (OSPRZET_OBJTYP('Magazynek', TO_DATE('03-01-2022','DD-MM-YYYY')));

UPDATE SPRAWA_OBJTAB SET ID_KOMIS_FK = (SELECT REF(K) FROM KOMISARIAT_OBJTAB K WHERE ID = 1) WHERE ID = 1;
UPDATE SPRAWA_OBJTAB SET ID_KOMIS_FK = (SELECT REF(K) FROM KOMISARIAT_OBJTAB K WHERE ID = 2) WHERE ID = 2;
UPDATE SPRAWA_OBJTAB SET ID_KOMIS_FK = (SELECT REF(K) FROM KOMISARIAT_OBJTAB K WHERE ID = 3) WHERE ID = 3;
UPDATE SPRAWA_OBJTAB SET ID_KOMIS_FK = (SELECT REF(K) FROM KOMISARIAT_OBJTAB K WHERE ID = 4) WHERE ID = 4;
UPDATE SPRAWA_OBJTAB SET ID_KOMIS_FK = (SELECT REF(K) FROM KOMISARIAT_OBJTAB K WHERE ID = 5) WHERE ID = 5;

UPDATE SPRAWA_OBJTAB SET DOWODY = DOWOD_NTABTYP();

INSERT INTO TABLE(SELECT S.DOWODY FROM SPRAWA_OBJTAB S WHERE ID = 1) VALUES (DOWOD_OBJTYP('NARZEDZIE ZBRODNI', TO_DATE('05-01-2022','DD-MM-YYYY'),ZDJECIE_VARTYP(ZDJECIE_OBJTYP('ZDJECIE PRZY OFIARZE', TO_DATE('11-11-2021','DD-MM-YYYY'),'21321312312312'))));
INSERT INTO TABLE(SELECT S.DOWODY FROM SPRAWA_OBJTAB S WHERE ID = 2) VALUES (DOWOD_OBJTYP('NARZEDZIE ZBRODNI', TO_DATE('05-01-2022','DD-MM-YYYY'),ZDJECIE_VARTYP(ZDJECIE_OBJTYP('MLOTEK', TO_DATE('11-11-2021','DD-MM-YYYY'),'21321312312312'))));
INSERT INTO TABLE(SELECT S.DOWODY FROM SPRAWA_OBJTAB S WHERE ID = 3) VALUES (DOWOD_OBJTYP('NARZEDZIE ZBRODNI', TO_DATE('05-01-2022','DD-MM-YYYY'),ZDJECIE_VARTYP(ZDJECIE_OBJTYP('KIJ', TO_DATE('11-11-2021','DD-MM-YYYY'),'21321312312312'))));
INSERT INTO TABLE(SELECT S.DOWODY FROM SPRAWA_OBJTAB S WHERE ID = 4) VALUES (DOWOD_OBJTYP('NARZEDZIE ZBRODNI', TO_DATE('05-01-2022','DD-MM-YYYY'),ZDJECIE_VARTYP(ZDJECIE_OBJTYP('PILKA', TO_DATE('11-11-2021','DD-MM-YYYY'),'21321312312312'))));
INSERT INTO TABLE(SELECT S.DOWODY FROM SPRAWA_OBJTAB S WHERE ID = 5) VALUES (DOWOD_OBJTYP('NARZEDZIE ZBRODNI', TO_DATE('05-01-2022','DD-MM-YYYY'),ZDJECIE_VARTYP(ZDJECIE_OBJTYP('KAMIEN', TO_DATE('11-11-2021','DD-MM-YYYY'),'21321312312312'))));

UPDATE SPRAWA_OBJTAB SET SWIADKOWIE = SWIADEK_NTABTYP();

INSERT INTO TABLE(SELECT S.SWIADKOWIE FROM SPRAWA_OBJTAB S WHERE ID = 1) VALUES (SWIADEK_OBJTYP(1,'Jan','Kowalski', '99120312345', TO_DATE('03-12-1999','DD-MM-YYYY'), ADRES_OBJTYP('Lewa', '1a', '12', 'Notki','12345'), '123421312', 'asdas@dsa.pl',ZDJECIE_VARTYP(ZDJECIE_OBJTYP('Zdjęcie profilowe2', TO_DATE('11-11-2021','DD-MM-YYYY'), '2211174522912251234')),'SWIADEK KORONNY'));
INSERT INTO TABLE(SELECT S.SWIADKOWIE FROM SPRAWA_OBJTAB S WHERE ID = 2) VALUES (SWIADEK_OBJTYP(1,'Jan','Kowalski', '99120312345', TO_DATE('03-12-1999','DD-MM-YYYY'), ADRES_OBJTYP('Miastowa', '13', '2', 'Klawiur','32133'), '123421312', 'asdas@dsa.pl',ZDJECIE_VARTYP(ZDJECIE_OBJTYP('Zdjęcie profilowe2', TO_DATE('11-11-2021','DD-MM-YYYY'), '2211174522912251234')),'SWIADEK KORONNY'));
INSERT INTO TABLE(SELECT S.SWIADKOWIE FROM SPRAWA_OBJTAB S WHERE ID = 3) VALUES (SWIADEK_OBJTYP(1,'Jan','Kowalski', '99120312345', TO_DATE('03-12-1999','DD-MM-YYYY'), ADRES_OBJTYP('Wiejska', '23', '3', 'Masun','12342'), '123421312', 'asdas@dsa.pl',ZDJECIE_VARTYP(ZDJECIE_OBJTYP('Zdjęcie profilowe2', TO_DATE('11-11-2021','DD-MM-YYYY'), '2211174522912251234')),'SWIADEK KORONNY'));
INSERT INTO TABLE(SELECT S.SWIADKOWIE FROM SPRAWA_OBJTAB S WHERE ID = 4) VALUES (SWIADEK_OBJTYP(1,'Jan','Kowalski', '99120312345', TO_DATE('03-12-1999','DD-MM-YYYY'), ADRES_OBJTYP('Grudzia', '21', '4', 'Szczecin','12313'), '123421312', 'asdas@dsa.pl',ZDJECIE_VARTYP(ZDJECIE_OBJTYP('Zdjęcie profilowe2', TO_DATE('11-11-2021','DD-MM-YYYY'), '2211174522912251234')),'SWIADEK KORONNY'));
INSERT INTO TABLE(SELECT S.SWIADKOWIE FROM SPRAWA_OBJTAB S WHERE ID = 5) VALUES (SWIADEK_OBJTYP(1,'Jan','Kowalski', '99120312345', TO_DATE('03-12-1999','DD-MM-YYYY'), ADRES_OBJTYP('Gdanska', '1', '5', 'Torun','12342'), '123421312', 'asdas@dsa.pl',ZDJECIE_VARTYP(ZDJECIE_OBJTYP('Zdjęcie profilowe2', TO_DATE('11-11-2021','DD-MM-YYYY'), '2211174522912251234')),'SWIADEK KORONNY'));

INSERT INTO ODCISK_OBJTAB VALUES(1,'Prawy kciuk',TO_DATE('03-12-2021','DD-MM-YYYY'), (SELECT REF(P) FROM POLICJANT_OBJTAB P WHERE ID =1), '321312312312312312');
INSERT INTO ODCISK_OBJTAB VALUES(2,'Prawy wskazujacy',TO_DATE('03-12-2021','DD-MM-YYYY'), (SELECT REF(P) FROM POLICJANT_OBJTAB P WHERE ID =1), '3213123123123dsada12312');
INSERT INTO ODCISK_OBJTAB VALUES(3,'Lewy kciuk',TO_DATE('05-12-2021','DD-MM-YYYY'), (SELECT REF(P) FROM POLICJANT_OBJTAB P WHERE ID =2), '32131dsa2312312312312');
INSERT INTO ODCISK_OBJTAB VALUES(4,'Prawy kciuk',TO_DATE('06-12-2021','DD-MM-YYYY'), (SELECT REF(P) FROM POLICJANT_OBJTAB P WHERE ID =3), '32131231dasdas2312312312');
INSERT INTO ODCISK_OBJTAB VALUES(5,'Prawy kciuk',TO_DATE('07-12-2021','DD-MM-YYYY'), NULL, '321312312312312312');
------- CREATE VIEWS --------------------

CREATE VIEW VIEW_ADRES_OBJV OF ADRES_OBJTYP
WITH OBJECT IDENTIFIER (KOD)
AS 
SELECT K.ADRES.ULICA, K.ADRES.NR_DOMU, K.ADRES.NR_MIESZKANIA, K.ADRES.MIASTO, K.ADRES.KOD FROM KOMISARIAT_OBJTAB K;

CREATE VIEW VIEW_zdjecia_OBJV OF zdjecie_OBJTYP
WITH OBJECT IDENTIFIER (opis)
AS 
SELECT opis, data_zebrania, obrazek FROM TABLE(SELECT p.zdjecia from POLICJANT_OBJTAB p where p.id =1);

CREATE VIEW VIEW_odznaki_OBJV OF odznaka_OBJTYP
WITH OBJECT IDENTIFIER (nazwa_odznaki)
AS 
SELECT nazwa_odznaki, cel FROM TABLE(SELECT p.odznaki from POLICJANT_OBJTAB p where p.id =1);


CREATE VIEW VIEW_zdjecia_dowody_OBJV OF zdjecie_OBJTYP
WITH OBJECT IDENTIFIER (opis)
AS 
SELECT opis, data_zebrania, obrazek  FROM TABLE(select zdjecia FROM TABLE(SELECT s.dowody from sprawa_OBJTAB s where s.id =1));

CREATE VIEW VIEW_polisy_OBJV OF polisa_OBJTYP
WITH OBJECT IDENTIFIER (typ_polisy)
AS 
SELECT typ_polisy, data_waznosci FROM TABLE(SELECT s.polisy from samochod_OBJTAB s where s.id =1);


------- DELETES -------------

DELETE FROM SPRAWA_OBJTAB WHERE ID_KOMIS_FK = (SELECT REF(K) FROM KOMISARIAT_OBJTAB K WHERE ID = 3);
DELETE FROM TABLE(SELECT P.ODZNAKI FROM POLICJANT_OBJTAB P WHERE ID = 3);
DELETE FROM TABLE(SELECT S.POLISY FROM SAMOCHOD_OBJTAB S WHERE ID = 1);
DELETE FROM TABLE(SELECT SWIADKOWIE FROM SPRAWA_OBJTAB where id =1);
DELETE FROM TABLE(SELECT DOWODY FROM SPRAWA_OBJTAB where id =1);

SELECT k.adres.miasto,k.adres.kod FROM  KOMISARIAT_OBJTAB k;
SELECT ZDJECIA FROM TABLE(SELECT DOWODY FROM SPRAWA_OBJTAB WHERE ID =2);
SELECT * FROM SPRAWA_OBJTAB WHERE ID_KOMIS_FK = (SELECT REF(K) FROM KOMISARIAT_OBJTAB K WHERE ID = 4);
SELECT p.adres.miasto,p.adres.kod FROM  policjant_OBJTAB p WHERE p.id =2;
SELECT p.data_urodzenia FROM  policjant_OBJTAB p order by p.data_urodzenia desc;
SELECT nazwa,wymagany_przeglad FROM TABLE(SELECT osprzet FROM policjant_OBJTAB p where p.id = 2);
SELECT * FROM TABLE(SELECT odznaki FROM policjant_OBJTAB p where p.id = 4);
SELECT id_komis_fk FROM policjant_OBJTAB p ;
SELECT OPIS FROM KOMISARIAT_OBJTAB k WHERE REF(K) = (SELECT ID_KOMIS_FK FROM SPRAWA_OBJTAB WHERE ID = 2);
SELECT adres FROM KOMISARIAT_OBJTAB k WHERE REF(K) = (SELECT ID_KOMIS_FK FROM POLICJANT_OBJTAB WHERE ID = 5);
SELECT ZDJECIA FROM TABLE(SELECT DOWODY FROM SPRAWA_OBJTAB WHERE ID = 5);